### ISSUE TITLE
Flipped basemap plots with some newer proj4 versions

### ISSUE THREAD

**Issue by megies** [obspy/obspy#2283]
This is just for future reference, since I was searching for this issue but could not find a corresponding ticket.

For some version combinations of basemap and proj4 map plots can be flipped East-West, see matplotlib/basemap#443.

See 9b8a737d3ff6869047778d1c9c25022edfa773f0 and 94356a114c1361295c04acf933646e71ac5a760f.

![48975995-51bae000-f033-11e8-9c75-4cd5a294ac7c](https://user-images.githubusercontent.com/1842780/51258646-bbf45f00-19aa-11e9-8774-ba2d51b9ab7c.png)

**Comment by JohnVidale** [comment]
Same problem for me, using "global".  I'm an ObsPy neophyte, and I didn't see how to avoid this problem for global plots.

**Comment by megies** [comment]
Glad that you found this issue then. :+1: 

We could think about popping a warning message on problematic matplotlib/proj4 version combos, maybe.. although it's a transitional problem and it might already be mostly gone until our next release.

But we should definitely check our package efforts (e.g. Linux distros like Debian , Ubuntu) if any of those are affected, because these are stuck with static version numbers.

**Comment by krischer** [comment]
How about just removing all `basemap` related features for the next big release? Most things are already nicely separated into `basemap` and `cartopy` functionality and `basemap` will be EOL very soon in any case: https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement

**Comment by JohnVidale** [comment]
Again, I just started with Python and ObsPy last month, so it may be a dumb problem, but making maps of the stations with inventory doesn’t work, some binhex-looking color scaling conflict.

**Comment by d-chambers** [comment]
> That sounds reasonable

Yep, it's even on the [road map](https://github.com/obspy/obspy/issues/2228)

**Comment by megies** [comment]
I think this issue can be closed, maybe somebody could double check if #2269 and #2313 added comprehensive warning messages and then there's nothing more we can do I guess?

**Comment by megies** [comment]
Seems like proj4 v6 is out, so we should check if it fixes things and we should change the dependency to `proj4 != 5`.

**Comment by mhearne-usgs** [comment]
Because of some taup issues fixed in https://github.com/obspy/obspy/pull/2280, I need to get obspy 1.1.1 installed on my Mac. However, when I try using conda (from conda forge), I get:
- obspy=1.1.1 -> proj4[version='<5']
However, there are no proj4 versions less than 5 currently available in conda forge for Mac OS.

Is there a workaround for me to get obspy 1.1.1 installed on my Mac?

**Comment by mhearne-usgs** [comment]
It looks like I can get it and pyasdf installed through pip for now...

**Comment by megies** [comment]
I wanted to see if proj4 v6 fixes the problem but now I can't reproduce it anymore. Anybody able to check if we can use proj4 v6 safely?

**Comment by d-chambers** [comment]
@megies,
I am not sure; the example [here](https://github.com/matplotlib/basemap/issues/443#issue-384050357) requires basemap, and the current basemap on conda-forge downgrades pyproj to 1.9.6 and proj4 to 5.2.0. Under these condition the problem still persists.

**Comment by d-chambers** [comment]
Maybe we can push this off to 2.0? If we are planning on dropping basemap in favor of cartopy at that point anyway it should make the problem go away.

**Comment by megies** [comment]
Well in any case it's a problem of dependency packages so it's not really our problem. But still it'd be nice to be able to rule out problematic dep versions through requirements/pinning, just so nobody stumbles into this again.
But for sure, we're not gonna hold up the release for this if everything else is ready. But.. still quite a few work intensive tickets in https://github.com/obspy/obspy/projects/2 that aren't being worked on right now, so we're not in immediate danger of miraculously having the release ready anyway
