### ISSUE TITLE
Stream.rotate() with multiple-station Streams not implemented?

### ISSUE THREAD

**Issue by liamtoney** [obspy/obspy#2623]
I ran into an issue today trying to rotate a Stream containing multiple stations from `'NE->RT'`. Each Trace has `stats.back_azimuth` defined; of course for different stations the values are different. I kept on getting weird results until I realized that the code for `Stream.rotate()` uses the `stats.back_azimuth` of the first Trace in the Stream. This clearly does not work for mixed-station Streams.

I guess this issue is either a feature request (for mixed-station Stream rotation) or a documentation suggestion (for more clarity that `st[0].stats.back_azimuth` is used **and overwrites the value for all other Traces**), since I had to dig a bit to realize that `Stream.rotate()` only works on single-station Streams.

My workaround for this is
```python
import numpy as np

for station in np.unique([tr.stats.station for tr in st]):
    st.select(station=station).rotate('NE->RT')
``` 
which is not much of a pain. Thanks all, I hope this isn't a dupe (didn't see it in my search).

**Setup details:**

* Python version: 3.8.3
* ObsPy version: 1.2.1 installed via conda
* macOS Mojave

**Comment by trichter** [comment]
Hi Liam, thanks for reporting this issue. This behaviour could definitely be improved. It's not only a problem for data of different stations and one event, but also for a single station and multiple events. Also, rotate will have problems if - for some reason - the traces in the stream are not "correctly" ordered. Related to #1918.

**Comment by liamtoney** [comment]
Thanks for your response, Tom.

> Also, rotate will have problems if - for some reason - the traces in the stream are not "correctly" ordered.

What do you mean by not correctly ordered?

**Comment by trichter** [comment]
> What do you mean by not correctly ordered?

Considering a stream of traces `ST1..Z, ST2..N, ST1..E, ST2..Z, ST1..N, ST2..E` rotate will mix data of different stations.

**Comment by liamtoney** [comment]
Yikes! Though I guess that is an unlikely scenario.

**Comment by megies** [comment]
This is indeed really not ideal.. without looking at all the detials, I think we should change it to something like this:

```python
class Stream():
    def rotate(self, *args, **kwargs):
        st_new = Stream()
        seed_ids = set([tr.id[:-1] + '?' for tr in st])
        for seed_id in seed_ids:
            net, sta, loc, cha = seed_id.split('.')
            st_new += self.select(net, sta, loc, cha)._rotate(*args, **kwargs)
        self.traces = st_new.traces
        return self
    def _rotate(self, ...):
        # current rotate() code
```

**Comment by seisman** [comment]
I also ran into the same issue today and it takes time to find out why a simple rotation doesn't work as expected.

It's very common that a Stream is for multiple stations and multiple events. It's intuitive to expect that the rotate method will use the trace's own `tr.stats.back_azimuth` attribute when doing the rotation.

IMHO, this is a severe bug and should be fixed ASAP. 

I'd like to help if you agree that this should be fixed.

**Comment by wangliang1989** [comment]
I feel that there is still a problem when one stream include multiple stations and one event.

**Comment by megies** [comment]
@seisman sure thing, please feel free to work on a PR! The above code snippet should go a long ways anyways and it's quite straight forward.. just never enough time in one day

**Comment by megies** [comment]
> It's intuitive to expect that the rotate method will use the trace's own `tr.stats.back_azimuth` attribute when doing the rotation.

without having looked at this in a while, our main focus and the main use case advertized should definitely be to have the rotation rely on proper metadata as an Inventory object. Those old legacy ways of crutches attached to `.stats` are all very patchy and should in general be discouraged by documentation =)
